### ISSUE TITLE
As a Quality manager I want to open clustered lists in the table view

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#689]
The map generates clusters when many data points are visualized and the user zooms out. Clicking on a cluster opens the info box with the list of records and their short name.

For quality tasks it would be super useful to open this list in the table view to be able to work on it, filter it and perhaps export it.

**Comment by sseppi** [comment]
We have to consider that, in the near future we will have also an Open Data Hub data Quality tool. and we need to elaborate also the connection with the other Open Data Hub tools.

**Comment by gappc** [comment]
@sseppi you commented:

> We have to consider that, in the near future we will have also an Open Data Hub data Quality tool. and we need to elaborate also the connection with the other Open Data Hub tools.

Is this a general remark that applies also to this issue, or is it a requirement just for this issue? In the former case, I'd create a new issue, because otherwise I think the requirement will get buried in this thread. Generally, connecting different tools involves having linkable resources (URLs), which will take us a long way.

About the topic "clustered lists in the table view": I have to take a look at the API's, I think there is a chance that we get the cluster bounding boxes from the map and reuse that for the Open Data Hub requests, but I need to do some testing., Should I take a look at it?

**Comment by gappc** [comment]
@sseppi i did now some experimentation with the content API, here are my findings.

First, it's possible to get the cluster bounding boxes and use that information to show the records of a cluster in the table view.

For example, the following link opens the map and selects the "Accommodation Mountain" dataset: https://databrowser.opendatahub.testingmachine.eu/?map=true&datasetIds=93317701-2ffa-4a6c-9fee-5d15a28a93ed

This gives 3 clusters with 19, 31 and 50 records (see image below)

![Image](https://github.com/user-attachments/assets/bfbd2e5e-6376-4ce0-8461-bb96017a0e59)

Here are the links with bounding boxes for the table view:
 
- 19 records: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?typefilter=32&polygon=bbc(11.752088%2046.7017,11.752088%2046.364104,11.197098%2046.364104,11.197098%2046.7017,11.752088%2046.7017)
- 31 records: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?typefilter=32&polygon=bbi(11.402639%2046.973781,11.402639%2046.500844,10.435467%2046.500844,10.435467%2046.973781,11.402639%2046.973781)
- 50 records: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?typefilter=32&polygon=bbc(12.3753%2047.079909,12.3753%2046.5168,11.5802%2046.5168,11.5802%2047.079909,12.3753%2047.079909)

While this works well, there is a problem in deciding if to use `bbc` or `bbi` to define the polygon (see [ODH documentation](https://github.com/noi-techpark/odh-docs/wiki/Geosorting-and-Locationfilter-usage#polygon-filter-functionality)):
 
- 19 records: here we need to use `bbc` to get the number of records that match the map
- 31 records: here we need to use `bbi` to get the number of records that match the map
- 50 records: here we need to use `bbc` to get the number of records that match the map

> Note that if possible I'd like to use `bbc` / `bbi` instead of the other options provided by the content API (e.g. wkt), because the timeseries API also uses `bbc` / `bbi`

At this point I'm stuck, because in general I don't know if it is necessary to use `bbc` or `bbi` for a given cluster. A solution could be to compute for all cluster points if they are inside the bounding box (use `bbc`) or if some points are on the bounding box (use `bbi`), but I'm not sure if this solution is correct.

@RudiThoeni do you have any idea on how to solve this problem?

**Comment by RudiThoeni** [comment]
@gappc To are in line with the mobility api i also implemented this `bbc` `bbi` bounding box functionality.
the difference is the POSTGIS query generated
bbi -->  ST_Intersects (https://postgis.net/docs/ST_Intersects.html)
bbc --> ST_Contains (https://postgis.net/docs/ST_Contains.html)

Since in tourism we have only Points, and the query is always if the polygon has this point inside i think lets use `bbc` always......

**Comment by RudiThoeni** [comment]
alright now i understand.
You compute the bounding box about min/max latitude/longitude  and bbc (which uses PostGIS ST_Contains) does not return all poinst which are on the bounding box border (which are exactly 4 points ;))

I checked the POSTGIS documentation and i saw that the ST_Contains Function gives only points which are "inside" the polygon and not the points which are on the borders. However ST_Covers should do the trick and return also the points on the borders.......

So now i changed to ST_Covers and it should work and return also all poinst on which are ON the borders of the boundingbox
(changed only on tourism.api.testingmachine.eu)........

**Comment by gappc** [comment]
@RudiThoeni thank you for the changes, but the problem persists, the numbers are at odd. I'll provide you a test branch in the next few days that outputs the relevant information such that we are able to test different settings.

**Comment by gappc** [comment]
@RudiThoeni I've deployed a version of the Data Browser at https://9.databrowser.gappc.net/ that shows the table view links of the cluster details. When you click on the links, you should get to the table view with the correct bounding box of the cluster set (see image below). Unfortunately, the numbers don't match.

![Image](https://github.com/user-attachments/assets/71168c29-a843-4805-91af-c886c3609c5e)

Please note, that this works only for the `content` API at the moment, the `timeseries` API gives me the error below when I try to pass e.g. URL https://9.databrowser.gappc.net/dataset/table/mobility/v2/flat/Bicycle?where=coordinate.bbi.(11.165031,46.677869,11.148548,46.656155) as described in the [timeseries OpenAPI definition](https://swagger.opendatahub.com/?url=https://mobility.api.opendatahub.com/v2/apispec#/Station%20%2F%20time%20series/get_v2__representation___edgeTypes_) (probably I'm messing up the syntax). Therefor, I did not implement linking to it yet.

```json
{
  "code": 400,
  "message": "SELECT EXPANSION ERROR: Syntax Error in WHERE clause: Alias 'coordinate' does not exist",
  "error": "Bad Request",
  "timestamp": 1740136598293
}
```

**Comment by RudiThoeni** [comment]
@gappc 
I tried now with the Accommodations Mountain as you wrote....
there are 100 Accommodations, and on your clusters they are divided into 31 - 19 - 50  = 100 alright
Then you calculate the Bounding Boxes and the api is filtered

I now tried to visualize the Bounding Boxes which are generated and the Accommodation points....

We see that here the first bounding box (blue) is right, but the second bounding box overlaps with the previous bounding box..... and the third bounding box with the second

![Image](https://github.com/user-attachments/assets/96ac2728-58f3-4d5f-bddd-7854fd13773c)

So with this strategy we get wrong numbers.....

A possible solution could be to draw a polygon that covers all points of a cluster, and pass this polygon to the api..... (is supported)

But not sure if we get too complicated by solving this way ;) what do you think?

**Comment by gappc** [comment]
Hey @RudiThoeni, very nice finding, that seems to explain the differences. Maybe the clusters are computed as a circle with center and radius and I just got the wrong output from them. I'll take a look at it and let you know.

**Comment by gappc** [comment]
@RudiThoeni @sseppi I did some more testing:

- using cluster center / radius values => did not work very well, because of issues when converting pixel sizes to meters (pixels are used by maplibre, the JavaScript map library in use)
- compute the convex hull of a cluster given its records => gave better results, but still the numbers don't match in any case

@RudiThoeni could you please revert your changes regarding `ST_Contains` and `ST_Contains`, maybe the convex hull works with one of these options?

Other possible reasons for the numbers to don't match are most likely rooted in differences between maplibre and POSTGIS, but I'm not 100% sure. Here is a incomplete list:

- different projections used (I don't think so, but I can not rule that out 100%)
- differences in number precision and rounding
- the precise criteria used to decide if a point is "inside" a cluster can differ
- other stuff I'm not aware of

Given the persisting problems, how should we proceed? This feature cost us already a lot of time and I'm not sure if we find a satisfying solution that works 100% of the time. One way could be that we use the POSTGIS `ST_Covers` function (contains more points) and let the user know, that the values between the map and the table won't always match. What is your opinion? Do you have other ideas?

**Comment by sseppi** [comment]
@gappc thank you for your effort in trying to find a solution that solves the problem in the 100% of the cases.

In my point of view, the feature is really interesting and I would suggest to go online with the most reliable solution we found till now. We could warn the user that is a beta feature and we re working to improve it, therefore the number of records included in a cluster could differ from the one shown on the Table.

I add @mrabans , since I would know also his opinion, since he proposed the feature.

**Comment by RudiThoeni** [comment]
@gappc @sseppi  i would not invest more time here, let us use it as it is with ST_Covers and add a warning that the numbers does not always match..... i don't see this as a big problem.....

**Comment by mrabans** [comment]
@gappc @RudiThoeni @sseppi I agree. It is not a problem if the cluster doesn't show all data points. Big players have the same issues on their maps, zooming in and out the data records shown differ slightly most times.

**Comment by gappc** [comment]
@sseppi @mrabans @RudiThoeni i've created PR #715 for this feature. The implementation computes the convex hull of the markers of a cluster and uses the `POLYGON` property of ODH to limit the results of the table view accordingly.

As mentioned in this topic, not all markers in a cluster may be displayed in the table view. The user is notified about this in the UI (see image below).

![Image](https://github.com/user-attachments/assets/688b0b7e-fff6-4679-a95f-aaf6533733f6)

You can test the implementation here: https://9.databrowser.gappc.net/

If everything works as expected, we can merge the PR.

**Comment by RudiThoeni** [comment]
Hi @gappc 
I tested everything seems to work good.
I will merge this PR......

What i am missing on this testing is a display of the complete results in the tableview, we see only the pages 

![Image](https://github.com/user-attachments/assets/894f68e8-d08e-41dc-840e-2c4be1a2c32a)

Is there a reason why we don't display this (@sseppi ), i would find that nice (I often have this tasks to check some counts after filtering etc...)  ...........

**Comment by gappc** [comment]
@RudiThoeni I agree that having the count somewhere is useful, issue #581 seems related.
